functionsDirectory = "C:\\Users\\gabri\\Documents\\Rekvo\\clients\\groupe-haque\\_github\\les-saveurs-du-maghreb\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\gabri\\Documents\\Rekvo\\clients\\groupe-haque\\_github\\les-saveurs-du-maghreb\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\gabri\\Documents\\Rekvo\\clients\\groupe-haque\\_github\\les-saveurs-du-maghreb\\netlify\\functions"

[build.environment]
NPM_FLAGS = "--legacy-peer-deps"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=2592000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]