import React from 'react';

interface RosetteProps {
  className?: string;
  opacity?: number;
  color?: string;
}

export const Rosette: React.FC<RosetteProps> = ({ 
  className = "", 
  opacity = 1,
  color = "currentColor" 
}) => {
  // We create a slice of the mandala and rotate it to create complexity without huge SVG size
  const petals = Array.from({ length: 12 }); // 12-point symmetry

  return (
    <svg 
      viewBox="0 0 400 400" 
      className={`pointer-events-none ${className}`}
      style={{ opacity }}
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        <linearGradient id="goldGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#C5A059" />
          <stop offset="50%" stopColor="#F5E6D3" />
          <stop offset="100%" stopColor="#C5A059" />
        </linearGradient>
      </defs>

      <g transform="translate(200, 200)">
        {/* Outer Rim Decoration */}
        <circle cx="0" cy="0" r="190" fill="none" stroke={color} strokeWidth="1" strokeDasharray="4 4" opacity="0.5" />
        <circle cx="0" cy="0" r="180" fill="none" stroke={color} strokeWidth="0.5" />

        {/* Main Geometric Pattern generated by rotation */}
        {petals.map((_, i) => (
          <g key={i} transform={`rotate(${i * 30})`}>
            {/* Primary Petal Shape */}
            <path 
              d="M0,0 L20,-140 Q40,-100 0,-180 Q-40,-100 -20,-140 Z" 
              fill="none" 
              stroke={color} 
              strokeWidth="0.8" 
            />
            {/* Inner Details */}
            <path 
              d="M0,0 L10,-80 Q20,-60 0,-100 Q-20,-60 -10,-80 Z" 
              fill="none" 
              stroke={color} 
              strokeWidth="0.5" 
              opacity="0.8"
            />
             {/* Connecting Arcs */}
            <path
                d="M-20,-140 Q0,-120 20,-140"
                fill="none"
                stroke={color}
                strokeWidth="0.5"
            />
            {/* Dots */}
            <circle cx="0" cy="-160" r="2" fill={color} />
            <circle cx="0" cy="-120" r="1.5" fill="none" stroke={color} />
            
            {/* Geometric interlacing lines */}
            <path d="M0,0 L15,-40 L0,-80 L-15,-40 Z" fill="none" stroke={color} strokeWidth="0.3" />
          </g>
        ))}

        {/* Center Star */}
        <g>
           <circle cx="0" cy="0" r="30" fill="none" stroke={color} strokeWidth="1" />
           <path d="M0,-30 L8,-8 L30,0 L8,8 L0,30 L-8,8 L-30,0 L-8,-8 Z" fill={color} opacity="0.2" />
           <path d="M0,-30 L8,-8 L30,0 L8,8 L0,30 L-8,8 L-30,0 L-8,-8 Z" fill="none" stroke={color} strokeWidth="0.5" />
        </g>
        
        {/* Middle Ring details */}
         <circle cx="0" cy="0" r="80" fill="none" stroke={color} strokeWidth="0.5" strokeDasharray="2 2" />
      </g>
    </svg>
  );
};